// El mismo catálogo que `STAFF_PERMISSIONS` del backend. El formulario solo
// ofrece códigos que el servidor acepta.
export const ROLE_PERMISSIONS = [
  { code: 'dashboard.view', label: 'View dashboard' },
  { code: 'products.view', label: 'View products' },
  { code: 'products.edit', label: 'Edit products' },
  { code: 'pricing.edit', label: 'Edit prices' },
  { code: 'costs.view', label: 'View costs' },
  { code: 'quotes.view', label: 'View quotes' },
  { code: 'quotes.create', label: 'Create quotes' },
  { code: 'quotes.edit', label: 'Edit quotes' },
  { code: 'quotes.send', label: 'Send quotes' },
  { code: 'quotes.convert', label: 'Convert quotes' },
  { code: 'quotes.delete', label: 'Delete quotes' },
  { code: 'carts.view', label: 'View carts' },
  { code: 'orders.view', label: 'View orders' },
  { code: 'orders.status', label: 'Change order status' },
  { code: 'orders.cancel', label: 'Cancel orders' },
  { code: 'payments.take', label: 'Take payments' },
  { code: 'payments.refund', label: 'Refund payments' },
  { code: 'payments.transaction_id', label: 'View payment ids' },
  { code: 'cores.manage', label: 'Manage cores' },
  { code: 'returns.manage', label: 'Manage returns' },
  { code: 'customers.view', label: 'View customers' },
  { code: 'customers.edit', label: 'Edit customers' },
  { code: 'customers.delete', label: 'Delete customers' },
  { code: 'tax_exemptions.review', label: 'Review tax exemptions' },
  { code: 'activity.view', label: 'View activity' },
  { code: 'users.manage', label: 'Manage users and roles' },
] as const
